sudo: false

language: php
php:
  - 7.2
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
  fast_finish: true

before_install:
   - export ALLOW_FAILURE=1; if [ "$TRAVIS_PHP_VERSION" != "hhvm" ] && [ "$TRAVIS_PHP_VERSION" != "nightly" ]; then export ALLOW_FAILURE=0; fi
   - pecl install mcrypt-1.0.2

install:
  - composer self-update
  - make install-deps

script:
  - composer validate
  - make lint 1>/dev/null
  - make check-style
  - make test-with-coverage-clover

after_success:
  - if [ "$ALLOW_FAILURE" = 0 ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$ALLOW_FAILURE" = 0 ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.xml; fi
